### ISSUE TITLE
Support for serializing geometry collections

### ISSUE THREAD

**Issue by tyrylu** [rory/rust-wkb#3]
Hello.
I needed a wkb conversion library and this one came up pretty high in the search results. However, i of course reached the unimplemented geometry collection serialization support. Adding it was not hard (the current rust nightly handled the recursive call just fine), so do you have any Rustc version support in mind, or would you accept a PR with the change?

**Comment by amandasaurus** [comment]
I don't have any particular rust version in mind. I would like it to still be useable for non-nightly versions. Is it possible for you to write a change which will compile on all versions? i.e. if you want support for `GeometryCollection` you need to use nightly, but you can still use the library for other things on stable?

**Comment by tyrylu** [comment]
I suppose that the change should work on stable as well, probably definitely only the latest stable, but you can test some older, if you want.
