### ISSUE TITLE
Typo in repo description

### ISSUE THREAD

**Issue by bl-ue** [rory/rust-wkb#9]
Hey @rory!  Cool project. 
I noticed that the description of the repository says

>Read & Write Well Know Binary in Rust

But didn't you mean [Well Known Binary](https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry#Well-known_binary) (from the readme)?

**Comment by amandasaurus** [comment]
I think I've fix that now. Right?

**Comment by bl-ue** [comment]
Yep, looks great!

**Comment by bl-ue** [comment]
(that response was super fast btw! 🚀)
